### ISSUE TITLE
Asking for informations !

### ISSUE THREAD

**Issue by MaximeDawn** [CapnKitten/Translucence#1]
Hey !! I loooove your Translucence theme ! The best theme i had yet !

Is there a way to contact you on Discord or something to talk about it, Instead of opening issues here ?

For now, i have a question, is there a way to customize it in code to avoid the separation between messages 
![image](https://user-images.githubusercontent.com/20993007/92412279-9d2c7880-f14b-11ea-8996-fe3502d01395.png)

**Comment by CapnKitten** [comment]
Add this to the theme file or custom CSS.
```css
.message-2qnXI6:not(.groupStart-23k01U),
.message-2qnXI6.compact-T3H92H {
	margin-top: 0 !important;
}
```

https://discord.com/invite/qZGGtxf
