### ISSUE TITLE
I prefered the old redish theme than the new aurora australlis one

### ISSUE THREAD

**Issue by Malakasskatakys** [CapnKitten/Translucence#19]
![vbngfvnghn](https://user-images.githubusercontent.com/43682361/125161740-a5e74400-e18c-11eb-9466-bb92e75d01f6.png)
You should add a switch that will be able to change between the new green theme to the old green one.

**Comment by Sturmivik** [comment]
The aurora theme looks cool, but the sunset theme is more to my liking. Is there a way for you to make a 'switch', like Malakasskatakys mentioned, so the user is able to switch back and forth between the two themes?

**Comment by DarkDevvv** [comment]
old one better
 pls send the png

**Comment by CapnKitten** [comment]
```css
:root {
  --app-bg: url(https://i.imgur.com/U8bSjj5.jpg);
  --app-accent: #d73d3d;
  --app-accent-rgb: 215,61,61;

  --textarea-color: 0,0,0;
  --textarea-alpha: 0.5;
  --textarea-alpha-focus: 0.65;

  --scrollbar-color: 0,0,0;
  --scrollbar-color-alt: 255,255,255;
}

.channelTextArea-rNsIhG {
    --textarea-alpha: 0.5;
}
```
Pasting that in either your custom css or the theme file will revert the changes.

**Comment by DarkDevvv** [comment]
i did already

**Comment by DarkDevvv** [comment]
could u just change back to the og

**Comment by DarkDevvv** [comment]
I HOSTED the THEME file on my GIT https://github.com/darkdevvv/translucence

**Comment by YunaraD0ki** [comment]
the old theme is not really working anymore... can you fix that?

**Comment by CapnKitten** [comment]
> the old theme is not really working anymore... can you fix that?

Paste this in your custom css.
```css
:root {
  --app-bg: url(https://i.imgur.com/U8bSjj5.jpg);

  --accent-hue: 0;
  --accent-saturation: 65.8%;
  --accent-lightness: 54.1%;

  --textarea-color: 0,0,0;
  --textarea-alpha: 0.5;
  --textarea-alpha-focus: 0.65;

  --scrollbar-color: 0,0,0;
  --scrollbar-color-alt: 255,255,255;
}

.channelTextArea-1FufC0 {
    --textarea-alpha: 0.35;
}
```
