### ISSUE TITLE
app accent isn't working like it used to

### ISSUE THREAD

**Issue by Not-AriStienfeld** [CapnKitten/Translucence#27]
![image](https://user-images.githubusercontent.com/56319363/149224163-8214bc2b-ee04-4e67-be86-c1dbd5d8075d.png)
![image](https://user-images.githubusercontent.com/56319363/149224172-01ea7fc1-e35a-4ec3-9f2f-aea417b3953c.png)
I'm not sure why it is doing this but a reload didn't fix it.

**Comment by CapnKitten** [comment]
The app accent variable was changed to `--app-accent-rgb` so there would be one variable controlling both solid and transparent accent colored elements. In your case it'd look like this:
```css
:root {
  --app-bg: url(URL.jpg);
  --app-accent-rgb: 255,0,0;
}
```
