### ISSUE TITLE
Custom Home button

### ISSUE THREAD

**Issue by Nooby69** [CapnKitten/Translucence#28]
can we add custom home button image?

**Comment by CapnKitten** [comment]
Can easily be done so by using the following code and changing the image url. Add it to your custom css or the theme file itself.

```css
.homeIcon-r0w4ny {
    display: none;
}

.tutorialContainer-1pL9QS .wrapper-3kah-n .childWrapper-1j_1ub {
    background-color: transparent;
}

.tutorialContainer-1pL9QS .wrapper-3kah-n .childWrapper-1j_1ub:before {
    position: absolute;
    content: " ";
    width: 24px;
    height: 24px;
    background-image: url('IMAGE_URL.png');
    background-size: contain;
}
```
