### ISSUE TITLE
Is there a way to reduce lag?

### ISSUE THREAD

**Issue by HyperSoop** [CapnKitten/Translucence#30]
You could say it's just the way the concept of themes works, but the lag is abyssmal. I have already disabled all blur effects, and it's still lagging, I suspect setting blur to 0 does not actually disable it?

**Comment by CapnKitten** [comment]
This'll remove the main background blur altogether. Let me know if it doesn't improve things.
```css
.layers-OrUESM {
    backdrop-filter: unset;
}
```
