### ISSUE TITLE
Background blur variable

### ISSUE THREAD

**Issue by rom4ukkk** [CapnKitten/Translucence#32]
Hey, could you add a variable to blur the whole background instead of the app elements?
Just wish this part (on screenshot) was blurry too
![image](https://user-images.githubusercontent.com/45468764/207007898-c35debdd-da1f-4cd7-b84a-54ba341e3603.png)

**Comment by CapnKitten** [comment]
There's no variable to add because the blur isn't supposed to be there by default. The code below will add it though; add it to your custom css.
```css
.app-3xd6d0:before {
    position: fixed;
    content: " ";
    width: 100vw;
    height: 100vh;
    top: 0;
    left: 0;
    pointer-events: none;
    backdrop-filter: blur(var(--app-blur));
}

.layers-OrUESM {
    backdrop-filter: unset;
}
```

**Comment by rom4ukkk** [comment]
This is exactly what I needed, thanks a lot!
There is one more small question, is it possible then to add a color overlay for the entire background, like for the sidebar and main parts?
![image](https://user-images.githubusercontent.com/45468764/207240097-72455675-8397-4d25-8030-4128aa451d43.png)

**Comment by CapnKitten** [comment]
Not exactly, but you can remove the app margin.
```css
root {
  --app-margin: 0px;
}
```
