### ISSUE TITLE
Mentions outline

### ISSUE THREAD

**Issue by JWTHDYTWA** [CapnKitten/Translucence#33]
Please add some variables to tweak mention outline. Because it's just too thick:
![изображение](https://user-images.githubusercontent.com/30724185/208307620-81ec1428-52b0-4eb9-bcc6-94aefbc6ff02.png)

**Comment by CapnKitten** [comment]
```css
.wrapper-30-Nkg.mentioned-Tre-dv {
    border-width: 1px;
    box-shadow: inset 0px 0px 6px 2px hsla(var(--mention-hsl), var(--mention-opacity)),
                0px 0px 9px 3px hsla(var(--mention-hsl), var(--mention-opacity));
}
```
