### ISSUE TITLE
Avatar glitch after status change

### ISSUE THREAD

**Issue by biguard1** [CapnKitten/Translucence#41]
## Description
Avatar disappears after status change

![2024-03-0902234](https://github.com/CapnKitten/Translucence/assets/102917281/9f89b64e-9c3f-4cec-a818-666f02980aa5)

## Why is it hppening?
For some reason discord creates new mask after status change, that applies to avatar:

![image](https://github.com/CapnKitten/Translucence/assets/102917281/868343a9-e2d0-45d1-a02f-7bf2ff2fb18f)

And this mask contains circle element, so this selector brokes the mask:
```css
.userProfileInner__8065b .wrapper_edb6e0 circle {
  fill: var(--profile-avatar-border-color);
}
```

## Possible solution
Change selector: ```.userProfileInner__8065b .wrapper_edb6e0 circle``` → ```.userProfileInner__8065b .wrapper_edb6e0 svg > circle```
